name:          编码规范 by @CrhFIT
description:   开发灵活，稳定，可维护的 HTML, CSS 和 JavaScript 代码的规范
url:           http://lab.roshanca.com/code-guide/

markdown:      kramdown
permalink:     pretty
highlighter:   rouge
